chmod +x ai_door_management_module.sh
mv door_management_fi door_management_files
mkdir door_management_files/door_configuration door_management_files/door_map door_management_files/door_logs
mv door_management_files/door_map_1.1 door_management_files/door_map
mv door_management_files/door_*.log door_management_files/door_logs
mv door_management_files/door_*.conf door_management_files/door_configuration
chmod +x ai_door_control.sh
